### ISSUE TITLE
How to find emoji name from character?

### ISSUE THREAD

**Issue by merwok** [alexmick/emoji-data-python#4]
Hello!  I have looked at the docs and the source code but didn’t find a function to go from :sparkles: to `"sparkles"`.  If there isn’t one, could it be added?  Thanks for considering

**Comment by bigsbug** [comment]
Hi @merwok  Can I do this?

**Comment by merwok** [comment]
At the moment I am waiting for a reply from the repo owner to know if the feature already exists, or if it would be considered a good addition.

FTR I found https://github.com/carpedm20/emoji/ which seems to be very popular and have a ton of features, but not this one (and seemed a bit big / complicated on a first impression).

**Comment by bigsbug** [comment]
I making the function and PR. you can accept

**Comment by merwok** [comment]
I would certainly have a look and try the function!

**Comment by bigsbug** [comment]
ok you can tell me any question about this

**Comment by alexmick** [comment]
Hi @merwok , thanks for the issue creation, you're right there is no direct way of achieving this. However this might do the trick
```python
emoji = emoji_data_python.get_emoji_regex().findall('Hello world ! 👋🏼 🌍 ❗')
codes = [hex(ord(e))[2:].upper() for e in emoji]  # Convert emoji to unified codes
names = [
    emoji.short_name
    for code in codes
    for emoji in emoji_data_python.emoji_data
    if emoji.unified == code  # Find emoji for that unified code
]
```
Returning:
```
['wave', 'skin-tone-3', 'earth_africa', 'exclamation']
```
I'm going to make a commit and a release to wrap the last two lines in handy functions !

**Comment by alexmick** [comment]
**Update** : you can now use `char_to_unified` in version [1.3.0](https://github.com/alexmick/emoji-data-python/releases) of the package :
```python
emoji = emoji_data_python.get_emoji_regex().findall('Hello world ! 👋🏼 🌍 ❗')
codes = [emoji_data_python.char_to_unified(e) for e in emoji]  # Convert emoji to unified codes
names = [
    emoji.short_name
    for code in codes
    for emoji in emoji_data_python.emoji_data
    if emoji.unified == code  # Find emoji for that unified code
]
```
The second line in my previous answer was not completely correct. This helper function better handles multi-codepoint emoji.

In your specific case @merwok
```python
>>> code = emoji_data_python.char_to_unified('✨')
>>> name = [emoji.short_name for emoji in emoji_data_python.emoji_data if emoji.unified == code][0]
>>> name
'sparkles'
```

Does this answer your question ?

**Comment by merwok** [comment]
This looks good! (only had to replace `for emoji in emoji_data_python` with `for emoji in emoji_data_python.emoji_data`).  Will probably have to wrap that second line in a function in order to return first match or None, unless you can be persuaded to add it  :slightly_smiling_face:

Thanks for the new version! :rocket:

**Comment by alexmick** [comment]
Well spotted, sorry for the mistake !

Indeed, we should be able to index the emoji data by unified code as well and get `None` if it doesn't exit. I think this part needs refactoring any way to speed thinks up and avoid loading everything in memory, will keep you informed when I get around to releasing that 🙂 

Closing this issue for now

**Comment by merwok** [comment]
Sounds good!

With get_emoji_regex, char_to_unified and that other function, I can achieve my original goal: replace emojis with a text version for indexing.  Thanks for the help!
